# Serviços de Administração

# Variaveis de ambiente

# DOMAIN=exemplo.com.br
# TZ=America/Sao_Paulo

# HOMARR_ENCRYPTION_KEY=chave_aleatoria_muito_longa_para_encriptacao
# HOMARR_DB_DATABASE=homarr
# HOMARR_DB_HOST=10.10.1.50
# HOMARR_DB_PORT=5432
# HOMARR_DB_USER=homarr
# HOMARR_DB_PASSWORD=senha_secreta

# HOMARR_REDIS_HOST=10.10.1.52
# HOMARR_REDIS_PORT=6379
# HOMARR_REDIS_USERNAME=default
# HOMARR_REDIS_PASSWORD=senha_redis
# HOMARR_REDIS_IDX=1

# N8N_ENCRYPTION_KEY=chave_aleatoria
# N8N_DB_DATABASE=N8N
# N8N_DB_HOST=10.10.1.50
# N8N_DB_PORT=5432
# N8N_DB_USER=n8n
# N8N_DB_SCHEMA=prod
# N8N_DB_PASSWORD=senha_secreta

services:
  homarr:
    container_name: homarr
    image: ghcr.io/homarr-labs/homarr:latest
    environment:
      TZ: ${TZ}
      # DOCKER_PORTS: "80" # INUTIL
      SECRET_ENCRYPTION_KEY: ${HOMARR_ENCRYPTION_KEY}
      # DB_DRIVER: node-postgres # better-sqlite3 se não quiser usar postgres
      # DB_DIALECT: postgresql # sqlite se não quiser usar postgres
      # DB_URL: postgresql://${HOMARR_DB_USER}:${HOMARR_DB_PASSWORD}@${HOMARR_DB_HOST}:5432/${HOMARR_DB_DATABASE}
      REDIS_IS_EXTERNAL: "true" # false se não quiser usar redis externo
      REDIS_HOST: ${HOMARR_REDIS_HOST}
      REDIS_PORT: ${HOMARR_REDIS_PORT}
      REDIS_USERNAME: ${HOMARR_REDIS_USERNAME}
      REDIS_PASSWORD: ${HOMARR_REDIS_PASSWORD}
      REDIS_DATABASE_INDEX: ${HOMARR_REDIS_IDX}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # Opcional, apenas se quiser integração com docker
      - ./data/homarr:/appdata
    # ports:
    #   - "80:80"
    networks:
      local:
        ipv4_address: 10.10.1.10
    restart: unless-stopped
    labels:
      # Traefik Labels
      - traefik.enable=true
      # ROTA SEM SSL
      - traefik.http.routers.homarr_not_ssl.rule=Host(`home.${DOMAIN}`)
      - traefik.http.routers.homarr_not_ssl.entrypoints=web
      # Redirecionamento HTTP → HTTPS
      - traefik.http.middlewares.homarr-https-redirect.redirectscheme.scheme=https
      - traefik.http.routers.homarr_not_ssl.middlewares=homarr-https-redirect
      # Rotas HTTPS
      - traefik.http.routers.homarr.rule=Host(`home.${DOMAIN}`)
      - traefik.http.routers.homarr.entrypoints=websecure
      - traefik.http.routers.homarr.tls.certresolver=le
      - traefik.http.routers.homarr.service=homarr
      - traefik.http.services.homarr.loadbalancer.server.port=7575

  ntfy:
    image: binwiederhier/ntfy
    container_name: ntfy
    command:
      - serve
    environment:
      TZ: ${TZ}
      NTFY_BASE_URL: "https://ntfy.${DOMAIN}"
      NTFY_BEHIND_PROXY: "true"
      NTFY_PROXY_TRUSTED_HOSTS: "10.10.1.2"
      NTFY_PROXY_FORWARDED_HEADER: x-forwarded-for
      NTFY_ATTACHMENT_CACHE_DIR: /var/cache/ntfy/attachments
      # enable-metrics: true
      # NTFY_CACHE_FILE: /var/lib/ntfy/cache.db
      # NTFY_AUTH_FILE: /var/lib/ntfy/auth.db
      # NTFY_AUTH_DEFAULT_ACCESS: deny-all
      # NTFY_AUTH_USERS: 'usuario:senha_hash:admin'
      # NTFY_ENABLE_LOGIN: true
    volumes:
      - ./data/ntfy:/etc/ntfy
      - ./data/ntfy/certs:/ntfy
      - ./data/ntfy/cache:/var/cache/ntfy
    # ports:
    #   - 80:80
    networks:
      local:
        ipv4_address: 10.10.1.11
    restart: unless-stopped
    healthcheck: # opcional: lembre-se de adaptar o host:porta para seu ambiente
      test:
        [
          "CMD-SHELL",
          "wget -q --tries=1 http://ntfy/v1/health -O - | grep -Eo '\"healthy\"\\s*:\\s*true' || exit 1",
        ]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      # Traefik Labels
      - traefik.enable=true
      # ROTA SEM SSL
      - traefik.http.routers.ntfy_not_ssl.rule=Host(`ntfy.${DOMAIN}`)
      - traefik.http.routers.ntfy_not_ssl.entrypoints=web
      # Redirecionamento HTTP → HTTPS
      - traefik.http.middlewares.ntfy-https-redirect.redirectscheme.scheme=https
      - traefik.http.routers.ntfy_not_ssl.middlewares=ntfy-https-redirect
      # Rotas HTTPS
      - traefik.http.routers.ntfy.rule=Host(`ntfy.${DOMAIN}`)
      - traefik.http.routers.ntfy.entrypoints=websecure
      - traefik.http.routers.ntfy.tls.certresolver=le
      - traefik.http.routers.ntfy.service=ntfy
      - traefik.http.services.ntfy.loadbalancer.server.port=80
      - traefik.http.services.ntfy.loadbalancer.passhostheader=true

  n8n:
    image: docker.n8n.io/n8nio/n8n
    container_name: n8n
    environment:
      N8N_HOST: "n8n.${DOMAIN}"
      WEBHOOK_URL: "https://n8n.${DOMAIN}/"
      N8N_PORT": "80" # INUTIL
      N8N_PROTOCOL: "https"
      N8N_PROXY_HOPS: 1 # para o Traefik
      NODE_ENV: "production"
      N8N_METRICS: "true" # Telemetria local para o prometheus
      N8N_DIAGNOSTICS_ENABLED: "false" # Telemetria do n8n
      N8N_HIRING_BANNER_ENABLED: "false" # Propaganda de trabalho
      N8N_VERSION_NOTIFICATIONS_ENABLED: "true" # Notificações de atualização
      N8N_PERSONALIZATION_ENABLED: "true" # Questões de personalização
      N8N_BLOCK_FILE_ACCESS_TO_N8N_FILES: "false" # Impedir erros de permissão
      N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS: "false" # Impedir erros de permissão
      N8N_RUNNERS_ENABLED: "true"
      GENERIC_TIMEZONE: "${TZ}"
      TZ: "${TZ}"
      N8N_N8N_ENCRYPTION_KEY: ${N8N_ENCRYPTION_KEY} # Pode remover para ser uma chave aleatoria
      # Database
      DB_TYPE: postgresdb # Mude para "sqlite" se não quiser
      DB_POSTGRESDB_HOST: "${N8N_DB_HOST}"
      DB_POSTGRESDB_PORT: "${N8N_DB_PORT}"
      DB_POSTGRESDB_DATABASE: "${N8N_DB_DATABASE}"
      DB_POSTGRESDB_SCHEMA: "${N8N_DB_SCHEMA}"
      DB_POSTGRESDB_USER: "${N8N_DB_USER}"
      DB_POSTGRESDB_PASSWORD: "${N8N_DB_PASSWORD}"
    volumes:
      - ./data/n8n:/home/node/.n8n
      - ./data/n8n/files:/files # Pasta de arquivos que os scripts do N8N pode acessar
    # ports:
    #   - "5678:5678"
    networks:
      local:
        ipv4_address: 10.10.1.12
    restart: unless-stopped
    labels:
      # Traefik Labels
      - traefik.enable=true
      # ROTA SEM SSL
      - traefik.http.routers.n8n_not_ssl.rule=Host(`n8n.${DOMAIN}`)
      - traefik.http.routers.n8n_not_ssl.entrypoints=web
      # Redirecionamento HTTP → HTTPS
      - traefik.http.middlewares.n8n-https-redirect.redirectscheme.scheme=https
      - traefik.http.routers.n8n_not_ssl.middlewares=n8n-https-redirect
      # Rotas HTTPS
      - traefik.http.routers.n8n.rule=Host(`n8n.${DOMAIN}`)
      - traefik.http.routers.n8n.entrypoints=websecure
      - traefik.http.routers.n8n.tls.certresolver=le
      - traefik.http.routers.n8n.service=n8n
      - traefik.http.services.n8n.loadbalancer.server.port=5678

  syncthing:
    image: lscr.io/linuxserver/syncthing:latest
    container_name: syncthing
    hostname: syncthing # opcional
    environment:
      # - PUID=1000 # ID do Usuário
      # - PGID=1000 # ID do Grupo
      - TZ=${TZ} # Seu fuso horário
    volumes:
      - ./data/syncthing/config:/config # Arquivos de configuração
      - ./data/syncthing/data:/data # Dados para serem sincronizados
    ports:
      # - 80:8384 # Interface Web
      - 22000:22000/tcp # Protocolo Syncthing
      - 22000:22000/udp # Protocolo Syncthing
      - 21027:21027/udp # Descoberta
    networks:
      local:
        ipv4_address: 10.10.1.13
    restart: unless-stopped
    labels:
      # Traefik Labels
      - traefik.enable=true
      # ROTA SEM SSL
      - traefik.http.routers.sync_not_ssl.rule=Host(`sync.${DOMAIN}`)
      - traefik.http.routers.sync_not_ssl.entrypoints=web
      # Redirecionamento HTTP → HTTPS
      - traefik.http.middlewares.sync-https-redirect.redirectscheme.scheme=https
      - traefik.http.routers.sync_not_ssl.middlewares=sync-https-redirect
      # Rotas HTTPS
      - traefik.http.routers.sync.rule=Host(`sync.${DOMAIN}`)
      - traefik.http.routers.sync.entrypoints=websecure
      - traefik.http.routers.sync.tls.certresolver=le
      - traefik.http.routers.sync.service=sync
      - traefik.http.services.sync.loadbalancer.server.port=8384

  harborguard:
    image: ghcr.io/harborguard/harborguard:latest
    container_name: harborguard
    environment:
      PORT: "8080" # Por algum motivo a porta precisa ser acima de 1000
      MAX_CONCURRENT_SCANS: "3"
      LOG_LEVEL: "info"
      HEALTH_CHECK_ENABLED: "true"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      local:
        ipv4_address: 10.10.1.14
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD-SHELL",
          'curl -fs http://localhost:8080/api/health | grep -q ''"status":"healthy"''',
        ]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      # Traefik Labels
      - traefik.enable=true
      # ROTA SEM SSL
      - traefik.http.routers.guard_not_ssl.rule=Host(`guard.${DOMAIN}`)
      - traefik.http.routers.guard_not_ssl.entrypoints=web
      # Redirecionamento HTTP → HTTPS
      - traefik.http.middlewares.guard-https-redirect.redirectscheme.scheme=https
      - traefik.http.routers.guard_not_ssl.middlewares=guard-https-redirect
      # Rotas HTTPS
      - traefik.http.routers.guard.rule=Host(`guard.${DOMAIN}`)
      - traefik.http.routers.guard.entrypoints=websecure
      - traefik.http.routers.guard.tls.certresolver=le
      - traefik.http.routers.guard.service=guard
      - traefik.http.services.guard.loadbalancer.server.port=8080

networks:
  local:
    external: true

