# Banco de dados

# Variaveis de ambiente

# PROD_PG_USER=postgres
# PROD_PG_PASSWORD=postgres
# PROD_PG_DATABASE=db
# DEV_PG_USER=postgres
# DEV_PG_PASSWORD=postgres
# DEV_PG_DATABASE=db

# PROD_REDIS_USERNAME=redis
# PROD_REDIS_PASSWORD=redis
# DEV_REDIS_USERNAME=redis
# DEV_REDIS_PASSWORD=redis

# TZ=America/Sao_Paulo

services:
  # PROD

  postgraseql-prod:
    image: postgres:alpine
    container_name: postgres-prod
    environment:
      POSTGRES_USER: ${PROD_PG_USER}
      POSTGRES_PASSWORD: ${PROD_PG_PASSWORD}
      POSTGRES_DB: ${PROD_PG_DATABASE}
      PGDATA: "/data"
      TZ: ${TZ}
      PGTZ: ${TZ}
    volumes:
      - ./data/postgresql/prod:/data
    networks:
      local:
        ipv4_address: 10.10.1.50
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis-prod:
    image: redis:alpine
    container_name: redis-prod
    command: redis-server --requirepass "${PROD_REDIS_PASSWORD}"
    environment:
      TZ: ${TZ}
      REDIS_USERNAME: ${PROD_REDIS_USERNAME} # Use Redis
      REDIS_PASSWORD: ${PROD_REDIS_PASSWORD}
    volumes:
      - ./data/redis/prod:/data
    # ports:
    #   - "6379:6379"
    networks:
      local:
        ipv4_address: 10.10.1.52
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # DEV

  postgresql-dev:
    image: postgres:alpine
    container_name: postgres-dev
    environment:
      POSTGRES_USER: ${DEV_PG_USER}
      POSTGRES_PASSWORD: ${DEV_PG_PASSWORD}
      POSTGRES_DB: ${DEV_PG_DATABASE}
      PGDATA: "/data"
      TZ: ${TZ}
      PGTZ: ${TZ}
    volumes:
      - ./data/postgresql/dev:/data
    networks:
      local:
        ipv4_address: 10.10.1.51
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis-dev:
    image: redis:alpine
    container_name: redis-dev
    command: redis-server --requirepass "${DEV_REDIS_PASSWORD}"
    environment:
      TZ: ${TZ}
      REDIS_USERNAME: ${DEV_REDIS_USERNAME} # Use redis
      REDIS_PASSWORD: ${DEV_REDIS_PASSWORD}
    volumes:
      - ./data/redis/dev:/data
    # ports:
    #   - "6379:6379"
    networks:
      local:
        ipv4_address: 10.10.1.53
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  local:
    external: true

